#!/usr/bin/env python3
"""Export public-safe dashboard JSON from registry CSV snapshots.

This script is intentionally conservative:
- unknown fields are excluded
- private fields are not exported
- output is marked as redacted scaffold data

Usage:
  python scripts/export_dashboard_json.py registries examples/dashboard/dashboard_export.generated.json
"""

import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ALLOWLIST = {
    "collectives": [
        "collective_id",
        "name",
        "coin",
        "coin_full_name",
        "scope",
        "asset_class",
        "status",
        "notes",
    ],
    "sub_collectives": [
        "sub_collective_id",
        "name",
        "coin",
        "coin_full_name",
        "parent_collective_id",
        "asset_class",
        "status",
        "notes",
    ],
    "members": [
        "member_id",
        "display_name",
        "platform_coin",
        "collective_coin",
        "primary_collective_coin",
        "sub_collective_coin",
        "status",
        "notes",
    ],
    "assets": [
        "asset_id",
        "asset_title",
        "asset_type",
        "creator_member_id",
        "collective_scope",
        "licence_type",
        "status",
        "notes",
    ],
    "projects": [
        "project_id",
        "project_title",
        "project_type",
        "collective_scope",
        "lead_member_id",
        "status",
        "notes",
    ],
    "mint_queue": [
        "mint_pack_id",
        "asset_id",
        "project_id",
        "token_standard_target",
        "network",
        "status",
        "review_required",
        "notes",
    ],
}

CSV_MAP = {
    "collectives": "collectives.csv",
    "sub_collectives": "sub_collectives.csv",
    "members": "members.csv",
    "assets": "assets.csv",
    "projects": "projects.csv",
    "mint_queue": "mint_queue.csv",
}

PRIVATE_FIELD_HINTS = [
    "email",
    "legal_name",
    "phone",
    "private",
    "secret",
    "seed",
    "password",
    "key",
    "drive_file_id",
    "drive_folder",
    "wallet_address",
    "repo_url",
]


def is_private_field(field_name: str) -> bool:
    lowered = field_name.lower()
    return any(hint in lowered for hint in PRIVATE_FIELD_HINTS)


def read_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def filter_row(row: dict, allowed_fields: list[str]) -> dict:
    output = {}
    for field in allowed_fields:
        if field in row and not is_private_field(field):
            output[field] = row.get(field, "")
    return output


def build_export(registry_dir: Path) -> dict:
    data = {
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "platform": {
            "name": "Create Your Collective",
            "coin": "CCC",
            "public_status": "alpha_scaffold",
        },
        "public_scope": "redacted_demo_or_member_safe_export",
        "redaction_status": "allowlist_filtered",
        "notes": "Generated by scripts/export_dashboard_json.py using conservative field allowlist.",
    }

    for section, filename in CSV_MAP.items():
        rows = read_csv(registry_dir / filename)
        allowed = ALLOWLIST[section]
        data[section] = [filter_row(row, allowed) for row in rows]

    return data


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: export_dashboard_json.py <registry_dir> <output_json>")
        return 2

    registry_dir = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    dashboard_export = build_export(registry_dir)
    output_path.write_text(json.dumps(dashboard_export, indent=2), encoding="utf-8")
    print(f"Wrote dashboard export to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
